#!/bin/bash

/usr/bin/binder-wait android.hardware.biometrics.fingerprint@2.1::IBiometricsFingerprint/default

SESSIONID=$(loginctl list-sessions | awk '/tty7/{print $1}')

while true
do
    SESSIONID=$(loginctl list-sessions | awk '/tty7/{print $1}')
    if [ ! -z $SESSIONID ]; then
       break
    fi
    sleep 1
done

while true
do
    export DISPSTAT=$(batman-helper wlrdisplay)
    export OLDSTAT=$(cat /home/droidian/.FP_STAT)
    echo "$DISPSTAT" > /home/droidian/.FP_STAT

    if [ "$OLDSTAT" != "$DISPSTAT" ]; then
        if [ "$DISPSTAT" == "yes" ]; then
            UNLOCKED=false
            while [ "$UNLOCKED" = false ]
            do
                /usr/libexec/fpd/droidian-fpd-unlocker $SESSIONID
                if [ $? != 0 ]; then
                   sleep 0.2
                else
                   UNLOCKED=true
                fi
            done
        fi
    else
        sleep 1
    fi
done
