#!/bin/bash

/usr/bin/binder-wait android.hardware.biometrics.fingerprint@2.1::IBiometricsFingerprint/default

SESSIONID=$(loginctl list-sessions | awk '/tty7/{print $1}')

delay() {
    read -t $1 < /dev/tty0
}

while true
do
    SESSIONID=$(loginctl list-sessions | awk '/tty7/{print $1}')
    if [ ! -z $SESSIONID ]; then
       break
    fi
    delay 1
done

while true
do
    export DISPSTAT=$(batman-helper wlrdisplay)
    export OLDSTAT=$(</home/droidian/.FP_STAT)
    echo "$DISPSTAT" > /home/droidian/.FP_STAT

    if [ "$OLDSTAT" != "$DISPSTAT" ]; then
        if [ "$DISPSTAT" == "yes" ]; then
            UNLOCKED=false
            while [ "$UNLOCKED" = false ]
            do
                /usr/libexec/fpd/droidian-fpd-unlocker $SESSIONID
                if [ $? != 0 ]; then
                   delay 0.2
                else
                   if [ -f /usr/lib/droidian/device/fpd-gkr-unlock ]; then
                       (pgrep -f "journalctl -q -f --since" | xargs kill) || true
                   fi
                   UNLOCKED=true
                fi
            done
        fi
    else
        delay 1
    fi
done
